// The operator handoff `npm run db:up` prints after provisioning the scoped
// least-privilege runtime user (SF3-1 / DBR-1 / D-026c).
//
// WHY THIS IS A MODULE AND NOT INLINE `console.log`s IN scripts/db-up.ts:
// the printed block is OPERATOR-FACING DOCUMENTATION of a real code seam, and it
// DRIFTED from that seam (SF2-1 red-team finding SF3-1): db-up used to print
// `SURREAL_USER`/`SURREAL_PASS` plus "connect at DATABASE auth level
// (Db.connect authLevel:'database')" as if the operator had to edit code. Both were
// wrong once the SF2-1 seam landed — an operator who followed db:up's OWN output
// configured vars the runtime does not read, the scoped signin never happened, and
// the dashboard silently stayed on the root path. db-up.ts runs `main()` on import,
// so its inline text can never be unit-tested; extracting the builder here makes the
// handoff a TESTED artifact that fails loudly when it drifts from the seam again.
//
// THE SEAM THIS DOCUMENTS (verified, do not paraphrase from memory):
//   • db/runtime-init.ts `resolveDbConnect` reads `SURREAL_RUNTIME_USER` +
//     `SURREAL_RUNTIME_PASS`. When BOTH are set it returns connect opts with
//     `authLevel:'database'` ITSELF — no source edit is required anywhere.
//   • A PARTIAL config (one set, the other blank) is refused with an honest reason
//     and NEVER falls back to root — falling back would connect with the wrong,
//     higher-privilege identity.
//   • When BOTH are unset the historical `SURREAL_USER`/`SURREAL_PASS` root path runs
//     byte-identically (additive opt-in, F-053). Once both ARE set, SURREAL_USER /
//     SURREAL_PASS are IGNORED by the runtime connect.
//   • db/client.ts `Db.connect` turns `authLevel:'database'` into the
//     `{namespace, database, username, password}` signin payload a `DEFINE USER … ON
//     DATABASE` user requires.
// The var names here MUST stay identical to .env.example's commented block (SF3-2) —
// doc, example env, and printed handoff are one spelling.

/** Thrown when the facts handed to the builder cannot produce an honest handoff. */
export class RuntimeHandoffError extends Error {
	override readonly name = 'RuntimeHandoffError';
}

/** The env var names the SF2-1 runtime-auth seam actually reads. Single source of spelling. */
export const RUNTIME_USER_VAR = 'SURREAL_RUNTIME_USER';
export const RUNTIME_PASS_VAR = 'SURREAL_RUNTIME_PASS';

/** Facts db:up knows after provisioning — everything the handoff is derived from. */
export interface RuntimeHandoffFacts {
	/** `SURREAL_WS` the datastore is listening on. */
	ws: string;
	/** Namespace the runtime user is scoped to. */
	namespace: string;
	/** Database the runtime user is scoped to. */
	database: string;
	/** The provisioned system-user name. */
	username: string;
	/** ROLES granted (fixed EDITOR for DBR-1) — echoed so the operator sees the scope. */
	role: string;
	/**
	 * True when `DEFINE USER IF NOT EXISTS` was a NO-OP because the user already
	 * existed. The pre-existing password stands and we do NOT know it — the handoff
	 * must say so instead of printing a fabricated value (F-008).
	 */
	alreadyExisted: boolean;
	/** True when the password was crypto-generated by this run (print-once). */
	generated: boolean;
	/** The generated password — ONLY meaningful when `generated && !alreadyExisted`. */
	password: string;
}

/**
 * Build the operator handoff block, line by line (caller `console.log`s each). Pure:
 * no I/O, no env reads — so the regression test can assert the exact text.
 *
 * Shadow paths, all covered:
 *   • nil/empty facts (blank ws/ns/db/username) → {@link RuntimeHandoffError}. Printing
 *     `SURREAL_RUNTIME_USER=` would be a plausible-looking lie the operator would paste.
 *   • user already existed → the password line says UNCHANGED + how to rotate; the
 *     generated field is never presented as authoritative.
 *   • password supplied via env → points back at the value the operator already set.
 *
 * @throws {RuntimeHandoffError} on empty ws/namespace/database/username, or on a
 *   `generated` claim with no password to show.
 */
export function runtimeHandoffLines(facts: RuntimeHandoffFacts): string[] {
	const ws = facts.ws?.trim() ?? '';
	const namespace = facts.namespace?.trim() ?? '';
	const database = facts.database?.trim() ?? '';
	const username = facts.username?.trim() ?? '';
	const missing = [
		['ws', ws],
		['namespace', namespace],
		['database', database],
		['username', username]
	]
		.filter(([, v]) => !v)
		.map(([k]) => k);
	if (missing.length) {
		throw new RuntimeHandoffError(
			`Cannot print the runtime handoff — empty ${missing.join(', ')}. ` +
				`An incomplete .env block is worse than none: the operator would paste a broken config.`
		);
	}
	if (facts.generated && !facts.alreadyExisted && !facts.password) {
		throw new RuntimeHandoffError(
			'Runtime password was reported as GENERATED but is empty — refusing to print a blank credential.'
		);
	}

	const out: string[] = [
		`[db:up] Runtime user provisioned: ${username} (ROLES ${facts.role}, scoped to DATABASE ` +
			`${namespace}/${database} — D-026c).`,
		'[db:up]   Scope (verified vs 2.6.5): CRUD on product tables YES; DEFINE USER / root+namespace ' +
			'admin / cross-database access NO.',
		'[db:up] To flip the dashboard runtime onto this scoped user, add these to .env (no code edit ' +
			'is required):',
		`          SURREAL_WS=${ws}`,
		`          SURREAL_NS=${namespace}`,
		`          SURREAL_DB=${database}`,
		`          ${RUNTIME_USER_VAR}=${username}`
	];

	if (facts.alreadyExisted) {
		// HONEST (F-008): IF NOT EXISTS was a no-op — it does NOT reset the password, so we
		// must NOT print a fresh/fabricated value. The credential from the FIRST provisioning
		// still stands, and this process never learned it.
		out.push(
			`          ${RUNTIME_PASS_VAR}=<unchanged — the user already existed; the password from its`,
			'                                FIRST provisioning is retained and is NOT known to this run.',
			`                                To rotate: REMOVE USER ${username} ON DATABASE, then re-run`,
			`                                db:up (optionally with ${RUNTIME_PASS_VAR} preset).>`
		);
	} else if (facts.generated) {
		// Printed ONCE, here only — never persisted, never logged again (D-026). A future
		// re-run does NOT reset this password, so it must be stored now.
		out.push(
			`          ${RUNTIME_PASS_VAR}=${facts.password}   # GENERATED — shown ONCE; store it now`
		);
	} else {
		out.push(`          ${RUNTIME_PASS_VAR}=<the ${RUNTIME_PASS_VAR} you already set for this run>`);
	}

	out.push(
		`[db:up]   Setting BOTH ${RUNTIME_USER_VAR} and ${RUNTIME_PASS_VAR} is all it takes: the runtime`,
		"[db:up]   connect (db/runtime-init.ts) signs in at DATABASE auth level ('database') on its own.",
		`[db:up]   Set BOTH or NEITHER — a partial config is REFUSED with an honest reason and never`,
		'[db:up]   falls back to root. While both are unset the runtime keeps the historical',
		'[db:up]   SURREAL_USER/SURREAL_PASS path unchanged; once both ARE set those two are IGNORED.'
	);
	return out;
}
